# Generated by Django 3.2.4 on 2021-06-16 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.BooleanField(verbose_name='доставка')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.IntegerField(verbose_name='номер телефона')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('payment_method', models.CharField(max_length=100, verbose_name='способ оплаты')),
                ('comments', models.TextField(verbose_name='комментии')),
                ('total', models.IntegerField(verbose_name='сумма заказа ')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Карттинка')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('weight', models.IntegerField(verbose_name='вес')),
                ('availability', models.BooleanField(default=True, verbose_name='наличие')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.category', verbose_name='катигория')),
            ],
        ),
    ]
